// Code generated by protoc-gen-go. DO NOT EDIT.
// source: WindmillFarm.proto

package Windmill

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WindmillListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WindmillListRequest) Reset()         { *m = WindmillListRequest{} }
func (m *WindmillListRequest) String() string { return proto.CompactTextString(m) }
func (*WindmillListRequest) ProtoMessage()    {}
func (*WindmillListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e313a93d90e2fd78, []int{0}
}

func (m *WindmillListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WindmillListRequest.Unmarshal(m, b)
}
func (m *WindmillListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WindmillListRequest.Marshal(b, m, deterministic)
}
func (m *WindmillListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WindmillListRequest.Merge(m, src)
}
func (m *WindmillListRequest) XXX_Size() int {
	return xxx_messageInfo_WindmillListRequest.Size(m)
}
func (m *WindmillListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WindmillListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WindmillListRequest proto.InternalMessageInfo

type WindmillListResponse struct {
	TotalCount                  int32           `protobuf:"varint,1,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`
	AvgPowerGeneratedLastMinute float64         `protobuf:"fixed64,2,opt,name=AvgPowerGeneratedLastMinute,proto3" json:"AvgPowerGeneratedLastMinute,omitempty"`
	AvgPowerGeneratedLastHour   float64         `protobuf:"fixed64,3,opt,name=AvgPowerGeneratedLastHour,proto3" json:"AvgPowerGeneratedLastHour,omitempty"`
	Windmills                   []*WindmillInfo `protobuf:"bytes,4,rep,name=Windmills,proto3" json:"Windmills,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}        `json:"-"`
	XXX_unrecognized            []byte          `json:"-"`
	XXX_sizecache               int32           `json:"-"`
}

func (m *WindmillListResponse) Reset()         { *m = WindmillListResponse{} }
func (m *WindmillListResponse) String() string { return proto.CompactTextString(m) }
func (*WindmillListResponse) ProtoMessage()    {}
func (*WindmillListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e313a93d90e2fd78, []int{1}
}

func (m *WindmillListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WindmillListResponse.Unmarshal(m, b)
}
func (m *WindmillListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WindmillListResponse.Marshal(b, m, deterministic)
}
func (m *WindmillListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WindmillListResponse.Merge(m, src)
}
func (m *WindmillListResponse) XXX_Size() int {
	return xxx_messageInfo_WindmillListResponse.Size(m)
}
func (m *WindmillListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WindmillListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WindmillListResponse proto.InternalMessageInfo

func (m *WindmillListResponse) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *WindmillListResponse) GetAvgPowerGeneratedLastMinute() float64 {
	if m != nil {
		return m.AvgPowerGeneratedLastMinute
	}
	return 0
}

func (m *WindmillListResponse) GetAvgPowerGeneratedLastHour() float64 {
	if m != nil {
		return m.AvgPowerGeneratedLastHour
	}
	return 0
}

func (m *WindmillListResponse) GetWindmills() []*WindmillInfo {
	if m != nil {
		return m.Windmills
	}
	return nil
}

type WindmillStatusRequest struct {
	WindmillId           string   `protobuf:"bytes,1,opt,name=WindmillId,proto3" json:"WindmillId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WindmillStatusRequest) Reset()         { *m = WindmillStatusRequest{} }
func (m *WindmillStatusRequest) String() string { return proto.CompactTextString(m) }
func (*WindmillStatusRequest) ProtoMessage()    {}
func (*WindmillStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e313a93d90e2fd78, []int{2}
}

func (m *WindmillStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WindmillStatusRequest.Unmarshal(m, b)
}
func (m *WindmillStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WindmillStatusRequest.Marshal(b, m, deterministic)
}
func (m *WindmillStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WindmillStatusRequest.Merge(m, src)
}
func (m *WindmillStatusRequest) XXX_Size() int {
	return xxx_messageInfo_WindmillStatusRequest.Size(m)
}
func (m *WindmillStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WindmillStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WindmillStatusRequest proto.InternalMessageInfo

func (m *WindmillStatusRequest) GetWindmillId() string {
	if m != nil {
		return m.WindmillId
	}
	return ""
}

type WindmillInfo struct {
	WindmillId                  string         `protobuf:"bytes,1,opt,name=WindmillId,proto3" json:"WindmillId,omitempty"`
	AvgPowerGeneratedLastMinute float64        `protobuf:"fixed64,2,opt,name=AvgPowerGeneratedLastMinute,proto3" json:"AvgPowerGeneratedLastMinute,omitempty"`
	AvgPowerGeneratedLastHour   float64        `protobuf:"fixed64,3,opt,name=AvgPowerGeneratedLastHour,proto3" json:"AvgPowerGeneratedLastHour,omitempty"`
	Status                      WindmillStatus `protobuf:"varint,4,opt,name=Status,proto3,enum=Windmill.WindmillStatus" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}       `json:"-"`
	XXX_unrecognized            []byte         `json:"-"`
	XXX_sizecache               int32          `json:"-"`
}

func (m *WindmillInfo) Reset()         { *m = WindmillInfo{} }
func (m *WindmillInfo) String() string { return proto.CompactTextString(m) }
func (*WindmillInfo) ProtoMessage()    {}
func (*WindmillInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e313a93d90e2fd78, []int{3}
}

func (m *WindmillInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WindmillInfo.Unmarshal(m, b)
}
func (m *WindmillInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WindmillInfo.Marshal(b, m, deterministic)
}
func (m *WindmillInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WindmillInfo.Merge(m, src)
}
func (m *WindmillInfo) XXX_Size() int {
	return xxx_messageInfo_WindmillInfo.Size(m)
}
func (m *WindmillInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_WindmillInfo.DiscardUnknown(m)
}

var xxx_messageInfo_WindmillInfo proto.InternalMessageInfo

func (m *WindmillInfo) GetWindmillId() string {
	if m != nil {
		return m.WindmillId
	}
	return ""
}

func (m *WindmillInfo) GetAvgPowerGeneratedLastMinute() float64 {
	if m != nil {
		return m.AvgPowerGeneratedLastMinute
	}
	return 0
}

func (m *WindmillInfo) GetAvgPowerGeneratedLastHour() float64 {
	if m != nil {
		return m.AvgPowerGeneratedLastHour
	}
	return 0
}

func (m *WindmillInfo) GetStatus() WindmillStatus {
	if m != nil {
		return m.Status
	}
	return WindmillStatus_Disconnected
}

func init() {
	proto.RegisterType((*WindmillListRequest)(nil), "Windmill.WindmillListRequest")
	proto.RegisterType((*WindmillListResponse)(nil), "Windmill.WindmillListResponse")
	proto.RegisterType((*WindmillStatusRequest)(nil), "Windmill.WindmillStatusRequest")
	proto.RegisterType((*WindmillInfo)(nil), "Windmill.WindmillInfo")
}

func init() { proto.RegisterFile("WindmillFarm.proto", fileDescriptor_e313a93d90e2fd78) }

var fileDescriptor_e313a93d90e2fd78 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x53, 0xcd, 0x4e, 0xf2, 0x40,
	0x14, 0xcd, 0x00, 0x1f, 0xf9, 0xb8, 0x10, 0x17, 0xa3, 0x98, 0x11, 0x23, 0x36, 0x5d, 0x75, 0x45,
	0x0c, 0x9a, 0xb8, 0x71, 0xe1, 0x2f, 0x68, 0x02, 0x09, 0x29, 0x24, 0xac, 0x2b, 0x1d, 0xcd, 0x24,
	0xed, 0x0c, 0xce, 0x0f, 0xbe, 0x93, 0x4f, 0xe5, 0x03, 0xf8, 0x0a, 0x26, 0xa6, 0x65, 0x8a, 0x25,
	0x58, 0x4d, 0xdc, 0xb8, 0x6b, 0xcf, 0x3d, 0xf7, 0x74, 0xce, 0xe9, 0x19, 0xc0, 0x53, 0xc6, 0xc3,
	0x98, 0x45, 0x51, 0x2f, 0x90, 0x71, 0x67, 0x2e, 0x85, 0x16, 0xf8, 0x7f, 0x86, 0xb5, 0xea, 0x37,
	0xdc, 0xc4, 0x6a, 0x09, 0xbb, 0x4d, 0xd8, 0xce, 0x06, 0x03, 0xa6, 0xb4, 0x4f, 0x9f, 0x0c, 0x55,
	0xda, 0x7d, 0x43, 0xb0, 0xb3, 0x8e, 0xab, 0xb9, 0xe0, 0x8a, 0xe2, 0x36, 0xc0, 0x44, 0xe8, 0x20,
	0xba, 0x12, 0x86, 0x6b, 0x82, 0x1c, 0xe4, 0xfd, 0xf3, 0x73, 0x08, 0x3e, 0x87, 0xfd, 0x8b, 0xc5,
	0xe3, 0x48, 0x3c, 0x53, 0xd9, 0xa7, 0x9c, 0xca, 0x40, 0xd3, 0x70, 0x10, 0x28, 0x3d, 0x64, 0xdc,
	0x68, 0x4a, 0x4a, 0x0e, 0xf2, 0x90, 0xff, 0x1d, 0x05, 0x9f, 0xc1, 0xde, 0x97, 0xe3, 0x5b, 0x61,
	0x24, 0x29, 0xa7, 0xfb, 0xc5, 0x04, 0x7c, 0x02, 0xb5, 0xec, 0xdc, 0x8a, 0x54, 0x9c, 0xb2, 0x57,
	0xef, 0xee, 0x76, 0x32, 0x64, 0xf5, 0x70, 0xc7, 0x1f, 0x84, 0xff, 0x49, 0x74, 0x4f, 0xa1, 0x99,
	0xbd, 0x8c, 0x75, 0xa0, 0x8d, 0xb2, 0x39, 0x24, 0x76, 0x57, 0x3b, 0x61, 0x6a, 0xb7, 0xe6, 0xe7,
	0x10, 0xf7, 0x15, 0x41, 0x23, 0x2f, 0xfa, 0xd3, 0xc2, 0x9f, 0xe7, 0x73, 0x04, 0xd5, 0xa5, 0x43,
	0x52, 0x71, 0x90, 0xb7, 0xd5, 0x25, 0x9b, 0xe1, 0xd8, 0x04, 0x2c, 0xaf, 0xfb, 0x9e, 0xb3, 0x98,
	0xf4, 0x09, 0x0f, 0xa0, 0x6e, 0xe3, 0x49, 0x9a, 0x81, 0x0f, 0x36, 0x15, 0x72, 0x4d, 0x6a, 0xb5,
	0x8b, 0xc6, 0xb6, 0x50, 0x23, 0x68, 0x5a, 0xea, 0xfa, 0xf7, 0xf1, 0x61, 0xe1, 0xc9, 0xac, 0x72,
	0xc1, 0x7f, 0xc5, 0x43, 0xc0, 0xd7, 0x4c, 0xcd, 0x04, 0xe7, 0x74, 0xa6, 0x7b, 0x52, 0xc4, 0x7d,
	0xc9, 0xc2, 0x5f, 0xcb, 0x5d, 0x36, 0x5e, 0x4a, 0xb5, 0xe9, 0x70, 0x32, 0xa6, 0x72, 0x41, 0xe5,
	0x7d, 0x35, 0xbd, 0x36, 0xc7, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x15, 0x28, 0xef, 0x7b, 0x63,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WindmillFarmClient is the client API for WindmillFarm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WindmillFarmClient interface {
	RequestList(ctx context.Context, in *WindmillListRequest, opts ...grpc.CallOption) (*WindmillListResponse, error)
	RequestWindmillStatus(ctx context.Context, in *WindmillStatusRequest, opts ...grpc.CallOption) (*WindmillInfo, error)
	DisconnectFromGrid(ctx context.Context, in *WindmillStatusRequest, opts ...grpc.CallOption) (*WindmillInfo, error)
}

type windmillFarmClient struct {
	cc grpc.ClientConnInterface
}

func NewWindmillFarmClient(cc grpc.ClientConnInterface) WindmillFarmClient {
	return &windmillFarmClient{cc}
}

func (c *windmillFarmClient) RequestList(ctx context.Context, in *WindmillListRequest, opts ...grpc.CallOption) (*WindmillListResponse, error) {
	out := new(WindmillListResponse)
	err := c.cc.Invoke(ctx, "/Windmill.WindmillFarm/RequestList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *windmillFarmClient) RequestWindmillStatus(ctx context.Context, in *WindmillStatusRequest, opts ...grpc.CallOption) (*WindmillInfo, error) {
	out := new(WindmillInfo)
	err := c.cc.Invoke(ctx, "/Windmill.WindmillFarm/RequestWindmillStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *windmillFarmClient) DisconnectFromGrid(ctx context.Context, in *WindmillStatusRequest, opts ...grpc.CallOption) (*WindmillInfo, error) {
	out := new(WindmillInfo)
	err := c.cc.Invoke(ctx, "/Windmill.WindmillFarm/DisconnectFromGrid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WindmillFarmServer is the server API for WindmillFarm service.
type WindmillFarmServer interface {
	RequestList(context.Context, *WindmillListRequest) (*WindmillListResponse, error)
	RequestWindmillStatus(context.Context, *WindmillStatusRequest) (*WindmillInfo, error)
	DisconnectFromGrid(context.Context, *WindmillStatusRequest) (*WindmillInfo, error)
}

// UnimplementedWindmillFarmServer can be embedded to have forward compatible implementations.
type UnimplementedWindmillFarmServer struct {
}

func (*UnimplementedWindmillFarmServer) RequestList(ctx context.Context, req *WindmillListRequest) (*WindmillListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestList not implemented")
}
func (*UnimplementedWindmillFarmServer) RequestWindmillStatus(ctx context.Context, req *WindmillStatusRequest) (*WindmillInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestWindmillStatus not implemented")
}
func (*UnimplementedWindmillFarmServer) DisconnectFromGrid(ctx context.Context, req *WindmillStatusRequest) (*WindmillInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisconnectFromGrid not implemented")
}

func RegisterWindmillFarmServer(s *grpc.Server, srv WindmillFarmServer) {
	s.RegisterService(&_WindmillFarm_serviceDesc, srv)
}

func _WindmillFarm_RequestList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WindmillListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WindmillFarmServer).RequestList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Windmill.WindmillFarm/RequestList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WindmillFarmServer).RequestList(ctx, req.(*WindmillListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WindmillFarm_RequestWindmillStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WindmillStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WindmillFarmServer).RequestWindmillStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Windmill.WindmillFarm/RequestWindmillStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WindmillFarmServer).RequestWindmillStatus(ctx, req.(*WindmillStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WindmillFarm_DisconnectFromGrid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WindmillStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WindmillFarmServer).DisconnectFromGrid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Windmill.WindmillFarm/DisconnectFromGrid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WindmillFarmServer).DisconnectFromGrid(ctx, req.(*WindmillStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WindmillFarm_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Windmill.WindmillFarm",
	HandlerType: (*WindmillFarmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestList",
			Handler:    _WindmillFarm_RequestList_Handler,
		},
		{
			MethodName: "RequestWindmillStatus",
			Handler:    _WindmillFarm_RequestWindmillStatus_Handler,
		},
		{
			MethodName: "DisconnectFromGrid",
			Handler:    _WindmillFarm_DisconnectFromGrid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "WindmillFarm.proto",
}
